config/routes.rb
Rails.application.routes.draw do
  root "root#index"
  namespace :dashboard do
    resources :subscribe_servers, only: [ :index, :show, :edit, :update, :destroy ]
  end
  get "/dashboard", to: "dashboard#index"
  mount MissionControl::Jobs::Engine, at: "/jobs"

  resource :inbox, only: :create
  resource :actor, only: :show
  get "/.well-known/webfinger", to: "webfinger#show"

  scope path: ".well-known" do
    scope module: :wellknown do
      get "nodeinfo", to: "nodeinfo#show"
    end
  end

  get "/nodeinfo/2.1", to: "nodeinfo#show"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/subscribe_server.rb
class SubscribeServer < ApplicationRecord
  validates :domain, presence: true
  validates :inbox_url, presence: true
end

app/controllers/dashboard/subscribe_servers_controller.rb
class Dashboard::SubscribeServersController < ApplicationController
  before_action :set_subscribe_server, only: %i[ show edit update destroy ]

  layout "dashboard"

  # GET /dashboard/subscribe_servers or /dashboard/subscribe_servers.json
  def index
    @subscribe_servers = SubscribeServer.all
  end

  # GET /dashboard/subscribe_servers/1 or /dashboard/subscribe_servers/1.json
  def show
  end

  # GET /dashboard/subscribe_servers/1/edit
  def edit
  end

  # PATCH/PUT /dashboard/subscribe_servers/1 or /dashboard/subscribe_servers/1.json
  def update
    respond_to do |format|
      if @subscribe_server.update(subscribe_server_params)
        format.html { redirect_to [ :dashboard, @subscribe_server ], notice: "Subscribe server was successfully updated." }
        format.json { render :show, status: :ok, location: @subscribe_server }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subscribe_server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboard/subscribe_servers/1 or /dashboard/subscribe_servers/1.json
  def destroy
    @subscribe_server.destroy!

    respond_to do |format|
      format.html { redirect_to dashboard_subscribe_servers_path, status: :see_other, notice: "Subscribe server was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscribe_server
      @subscribe_server = SubscribeServer.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def subscribe_server_params
      params.expect(subscribe_server: [ :domain, :inbox_url, :delivery_suspend, :domain_block ])
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @rebroadcast_counters = 7.downto(0).map do |num|
      key = num.days.ago.strftime("%Y-%m-%d")
      value = Rails.cache.read(key)

      [ key, value ? value : 0 ]
    end
  end
end

app/views/dashboard/subscribe_servers/_form.html.erb
<%= form_with(model: [:dashboard, subscribe_server], class: "flex flex-col gap-4") do |form| %>
  <% if subscribe_server.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(subscribe_server.errors.count, "error") %> prohibited this subscribe_server from being saved:</h2>

      <ul>
        <% subscribe_server.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-col gap-2">
    <%= form.label :domain %>
    <%= form.text_field :domain, readonly: true %>
  </div>

  <div class="flex flex-col gap-2">
    <%= form.label :inbox_url %>
    <%= form.text_field :inbox_url, readonly: true %>
  </div>

  <div class="flex flex-col gap-2">
    <%= form.label :delivery_suspend %>
    <%= form.checkbox :delivery_suspend %>
  </div>

  <div class="flex flex-col gap-2">
    <%= form.label :domain_block %>
    <%= form.checkbox :domain_block %>
  </div>

  <div>
    <%= form.submit "Update", class: "border-solid border-2 border-slate-950 bg-cyan-400 text-white p-3" %>
  </div>
<% end %>

app/views/dashboard/subscribe_servers/_subscribe_server.html.erb
<div id="<%= dom_id subscribe_server %>" class="flex flex-col gap-3">
  <div>
    <h3>Domain</h3>
    <p class="underline">
      <%= subscribe_server.domain %>
    </p>
  </div>

  <div>
    <h3>Inbox URL</h3>
    <p class="underline">
      <%= subscribe_server.inbox_url %>
    </p>
  </div>

  <div>
    <h3>Delivery Suspend</h3>
    <p class="underline">
      <%= subscribe_server.delivery_suspend %>
    </p>
  </div>

  <div>
    <h3>Domain Block</h3>
    <p class="underline">
      <%= subscribe_server.domain_block %>
    </p>
  </div>
</div>

app/views/dashboard/subscribe_servers/edit.html.erb
<div class="flex flex-col gap-4">
  <% content_for :title, "Editing subscribe server" %>

  <h1 class="text-2xl">Editing subscribe server</h1>

  <%= render "form", subscribe_server: @subscribe_server %>

  <div>
    <%= link_to "Show this subscribe server", [:dashboard, @subscribe_server], class: "underline hover:text-cyan-500 visited:text-purple-600" %> |
    <%= link_to "Back to subscribe servers", dashboard_subscribe_servers_path, class: "underline hover:text-cyan-500 visited:text-purple-600" %>
  </div>
</div>

app/views/dashboard/subscribe_servers/index.html.erb
<div class="flex flex-col gap-3">
  <p style="color: green"><%= notice %></p>

  <% content_for :title, "Subscribe servers" %>

  <h1 class="text-2xl">Subscribe servers</h1>

  <div id="subscribe_servers mt-4">
    <% @subscribe_servers.each do |subscribe_server| %>
      <p>
        <%= link_to subscribe_server.domain, [:dashboard, subscribe_server], class: "underline hover:text-cyan-500 visited:text-purple-600" %>
      </p>
    <% end %>
  </div>
</div>

app/views/dashboard/subscribe_servers/show.html.erb
<div class="flex flex-col gap-4">
  <p style="color: green"><%= notice %></p>

  <%= render @subscribe_server %>

  <div class="flex flex-col gap-4">
    <div>
      <%= link_to "Edit this subscribe server", edit_dashboard_subscribe_server_path(@subscribe_server), class: "underline hover:text-cyan-500 visited:text-purple-600" %> |
      <%= link_to "Back to subscribe servers", dashboard_subscribe_servers_path, class: "underline hover:text-cyan-500 visited:text-purple-600" %>
    </div>

    <%= button_to "Destroy this subscribe server", [:dashboard, @subscribe_server], method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "border-solid border-2 border-slate-950 bg-red-500 text-white p-2" %>
  </div>
</div>