config/routes.rb
Rails.application.routes.draw do
  root "root#index"
  namespace :dashboard do
    resources :subscribe_servers, only: [ :index, :show, :edit, :update, :destroy ]
  end
  get "/dashboard", to: "dashboard#index"
  mount MissionControl::Jobs::Engine, at: "/jobs"

  resource :inbox, only: :create
  resource :actor, only: :show
  get "/.well-known/webfinger", to: "webfinger#show"

  scope path: ".well-known" do
    scope module: :wellknown do
      get "nodeinfo", to: "nodeinfo#show"
    end
  end

  get "/nodeinfo/2.1", to: "nodeinfo#show"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Activity Pub Relay" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>

    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Activity Pub Relay" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if request.path.match?(/dashboard/) %>
      <div class="flex divide-x divide-neutral-950 h-screen">
        <div class="flex flex-col gap-3 p-4 w-1/6">
          <%= link_to "Subscribe Servers", dashboard_subscribe_servers_path, class: "text-2xl underline" %>
          <%= link_to "Job Dashboard", "/jobs", class: "text-2xl underline" %>
          <%= link_to "OTP settings", rodauth.two_factor_manage_path, class: "text-2xl underline" %>
        </div>
        <div class="w-5/6 p-4">
          <div class="container p-4">
            <%= yield %>
          </div>
        </div>
      </div>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>